name: medireview
favicon: null
layout_spectrum: 0.99788
typography_spectrum: 0.30223051202483475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5362094193696976
  lightness: 0.663586157374084
  saturation: 0.5835634549148381
  rhythmicContrast: 0.8850603536702693
purpose: []
